### ISSUE TITLE
helm: cert-manager

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1040]
### Additional context

- ...

### To-Do

- [x] add cert-manager
   - [x] helm chart && gtilab ci
   - [x] correct install in k8s
- [ ] https://blog.jetstack.io/blog/cert-manager-google-cas-issuer/
- [ ] https://cert-manager.io/
- [x] prom && grafana
