### ISSUE TITLE
Learn kubernetes-operator

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#110]
### ToDo

- [x] Init service
- [ ] Get list svc
- [ ] Save as link short (over API)

### Links

- [x] https://github.com/operator-framework/operator-sdk
- [ ] [Creating Custom Kubernetes Operators](https://www.magalix.com/blog/creating-custom-kubernetes-operators)
- [x] [Best tutorial](https://www.magalix.com/blog/the-best-kubernetes-tutorials)
- https://blog.pridybailo.com/%d0%bf%d0%b8%d1%88%d0%b5%d0%bc-%d0%be%d0%bf%d0%b5%d1%80%d0%b0%d1%82%d0%be%d1%80-%d0%b4%d0%bb%d1%8f-kubernetes/
