### ISSUE TITLE
ansible [tutorial]

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1250]
### TODO

- [ ] [Ansible идемпотентный. Алексей Соколов](https://habr.com/ru/post/536340/)
- [ ] [Xудшие практики для Ansible. Георгий Шуклин](https://habr.com/ru/post/536256/)
- [ ] [4 lines of code to improve your Ansible play](https://opensource.com/article/21/1/improve-ansible-play)
- [ ] [10 ways Ansible is for everyone](https://opensource.com/article/21/1/ansible)
