### ISSUE TITLE
add cache service

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#143]
```
EDGE<-->Cache<-->ShortLink
```

### TODO

- [x] go-cache as example https://github.com/go-redis/cache
- [ ] algorithm
  - [ ] LRU cache
  
##### Example package

- [ ] [The State of Caching in Go](https://dgraph.io/blog/post/caching-in-go/)
- [ ] https://github.com/hashicorp/golang-lru
