### ISSUE TITLE
Link - move to new service

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1689]
### TODO:

- [x] DI move to project dir
- [x] Link service CRUD (recovery)
- [x] Check test
- [ ] CI
  - [x] Add Helm chart
  - [ ] Deploy new service
  - [ ] Nginx-ingress gRPC routing
- [x] DDD
  - [x] Application: create subdir
