### ISSUE TITLE
New lib: SagaManager

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1691]
### TODO

- [ ] copy https://github.com/itimofeev/go-saga
- [ ] https://github.com/dty1er/saga-in-real-world

### TODO
- [ ] Write test
  - [x] check concurrency
- [ ] Optimization/profiling
- [x] Logger
- [x] Trace
- [ ] Store???
  - [ ] Write Log for recovery
  - [ ] Use log for reject???
- [ ] State Saga???
- [ ] Healthchecker
  - [ ] Prometheus
  - [ ] Block bad-saga
- [ ] Docs
  - [ ] Export DAG as PNG

### Optional
- Step
  - [ ] retry run step
  - [ ] reject by timeout
  - [ ] optional reject for step
- [ ] Sage condition
  - [ ] Catch() - run if fail main func??? or fail Reject function???
- [ ] Sage hook
  - [ ] if success
  - [ ] if fail? 

### Link

- [x] https://habr.com/ru/post/544042/
- [x] https://habr.com/ru/company/true_engineering/blog/412793/
- [x] https://habr.com/ru/company/oleg-bunin/blog/418235/
