### ISSUE TITLE
docs: asciinema

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1715]
### TODO:

move to `./docs/asciinema`

- [ ] run microservices in minikube
- [ ] run microservices in docker-compose
- [ ] make generate (go generate)
- [ ] make test

**Comment by batazor** [comment]
https://asciinema.org/a/ElqLr756zSjpwFCuAQgSbXxBB
