### ISSUE TITLE
improve makefile v2

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#187]
### To-Do

- [ ] https://www.reddit.com/r/golang/comments/e7t2be/using_makefiles_for_go
- [ ] https://github.com/thockin/go-build-template
- [ ] https://danishpraka.sh/2019/12/07/using-makefiles-for-go.html
- [ ] https://tech.davis-hansson.com/p/make/
