### ISSUE TITLE
try Bazel

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#188]
### ToDo

- [ ] build go: shortlink
- [ ] build go: logger
- [ ] update makefile
- [ ] run from docker image
- [ ] build docker images
- [ ] publish docker image to gcr.io
- [ ] add lintint
- [ ] add testing
- [ ] k8s/helm support?
- [ ] bazel awesome
- [ ] etc... 

### Link

- https://bazel.build/
- [ ] https://about.gitlab.com/blog/2020/09/01/using-bazel-to-speed-up-gitlab-ci-builds/
- [ ] https://github.com/bazelbuild/rules_go
- [ ] https://github.com/bazelbuild/bazel-gazelle
- [ ] https://github.com/bazelbuild/bazel-gazelle/issues/591
- [ ] https://medium.com/@tduble94/create-go-monorepo-with-go-modules-and-bazel-95f00cf571d3

**Comment by batazor** [comment]
another time
