### ISSUE TITLE
Pattern "Memento"

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#1882]
### Docs

- [ ] [Суть паттерна](https://refactoring.guru/ru/design-patterns/memento)

### TODO

- [x] create table `EVENTS`

| entity_id | entity_type | entity_data |
|---|---|---|
| 1 | createOrder | {json} |
| 2 | approveOrder | {json} |

- [x] create table `SNAPSHOTS`

| entity_id | entity_type | entity_data |
|---|---|---|
| 2 | createOrder | {json} |

---

![Screenshot from 2021-05-21 20-41-43](https://user-images.githubusercontent.com/1643797/119177490-0f907f00-ba75-11eb-8687-92a18ab21902.png)
