### ISSUE TITLE
Add ansible role for deploy to vagrant

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#21]
### ToDo

- [x] vagrant
- [x] Install Docker/Docker-compose
- [x] Run this service
- [x] Test ([use molecule](https://molecule.readthedocs.io/en/latest/))

### Links:
- https://habr.com/ru/post/437216/
- https://robertdebock.nl/
- https://gitlab.com/nayls-project/devops-pets/raspberry-ci
- [How to Use Ansible to Install and Set Up Apache on Ubuntu 18.04](https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-apache-on-ubuntu-18-04)
