### ISSUE TITLE
Learn DAO-concept

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#2274]
### TODO:

- [x] https://habr.com/ru/post/263033/
- [x] https://www.tutorialspoint.com/design_pattern/data_access_object_pattern.htm
- [x] https://intellect.icu/shablon-dao-primery-dostoinstva-i-nedostatki-9502
- [ ] https://javatutor.net/articles/j2ee-pattern-data-access-object
- [x] https://tproger.ru/projects/pattern-data-access-object/
