### ISSUE TITLE
Try Nuxt

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#255]
### To-Do

- [x] travis CI
  - [x] multi build
- [x] page links
  - [x] table
- [x] https://github.com/nuxt-community/router-module
  - [ ] use config for generation `menu multi level`
- [ ] https://vuetifyjs.com/ru/
- [x] https://github.com/nuxt-community/robots-module
- [x] https://github.com/nuxt-community/sitemap-module

### Link

- ...
