### ISSUE TITLE
pingcap/chaos-mesh

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#275]
### To-Do

- [x] pod-kill: Simulates Kubernetes Pods being killed
- [x] pod-failure: Simulates Kubernetes Pods being continuously unavailable
- [x] network-delay: Simulates network delay
- [x] network-loss: Simulates network packet loss
- [x] network-duplication: Simulates network packet duplication
- [x] network-corrupt: Simulates network packet corruption
- [x] network-partition: Simulates network partition
- [x] I/O delay: Simulates file system I/O delay
- [x] I/O errn

o: Simulates file system I/O errors

os: Simulate file system faults such as I/O delay, read/write errors, etc.

### Link

- https://github.com/pingcap/chaos-mesh
