### ISSUE TITLE
Add API: grpc, grpc-web

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#29]
### To-Do

- [x] grpc-gateway: redirect
- [x] grpc-gateway: delete
- [ ] format response <-> http-chi
- [x] generate swagger-docs

### Link

- https://github.com/grpc-ecosystem/grpc-gateway/blob/master/third_party/googleapis/google/api/annotations.proto
- https://blog.maddevs.io/go-rest-%D0%B8%D0%BB%D0%B8-grpc-f5d52d7ffff6
- https://habr.com/ru/post/337716/
