### ISSUE TITLE
ui: next.js

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#327]
### To-Do

- [ ] Add test

- UI
  - [ ] [Calendar](https://reactnicedates.hernansartorio.com/)

### Link

- [ ] https://nextjs.org/
- [ ] https://www.mongodb.com/blog/post/building-modern-applications-with-nextjs-and-mongodb
