### ISSUE TITLE
nats

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#334]
### To-Do

- [ ] Add test

### Link

- NATS 4 step-by-step
   - [ ] https://medium.com/@dale.bingham_30375/using-nats-to-implement-service-mesh-functionality-part-1-service-discovery-5f2e6088843b
    - [ ] https://medium.com/@dale.bingham_30375/using-nats-to-implement-service-mesh-functionality-part-2-security-e963d63583f8
    - [ ] https://medium.com/@dale.bingham_30375/using-nats-to-implement-service-mesh-functionality-part-3-metrics-tracing-alert-observability-f77cf5ab7db1
    - [ ] https://medium.com/@dale.bingham_30375/using-nats-to-implement-service-mesh-functionality-part-4-load-balancing-and-routing-control-a015eadeca4b
