### ISSUE TITLE
DTO: Data Transfer Object

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#339]
### To-Do

- [ ] Add test

### Link

- [ ] http://design-pattern.ru/patterns/data-transfer-object.html
- [ ] https://habr.com/ru/post/268371/
- [ ] [link](https://www.reddit.com/r/golang/comments/6xgzmp/model_to_dto_mapper_my_first_experience_with_go/)
- [ ] https://habr.com/ru/post/430300/
