### ISSUE TITLE
listener bot

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#346]
### To-Do

- [x] Connect to Telegram channel
- [ ] Parse link
- [x] Add event to MQ
- [x] Subscribe to MQ [shortlink]

### Link

- [ ] https://go-telegram-bot-api.github.io/getting-started/
