### ISSUE TITLE
Add Logger interface

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#40]
### ToDo

- [x] Interface
- [x] Zap implementation
- [x] Logrus implementation
- [x] Context for close method
- [ ] Test

### Link

- [x] https://forum.golangbridge.org/t/whats-so-bad-about-the-stdlibs-log-package/1435/16
- [x] https://www.mountedthoughts.com/golang-logger-interface/
- [x] https://blog.gopheracademy.com/advent-2016/context-logging/
- [x] https://github.com/sandipb/zap-examples/tree/master/src/customencoder
- [x] https://dev-journal.in/2019/05/27/adding-uber-go-zap-logger-to-golang-project/
- [x] https://dave.cheney.net/tag/logging
- [x] http://notes.burke.libbey.me/context-and-logging/
