### ISSUE TITLE
devops: gitlab ci-pipeline

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#43]
### ToDo

- [x] Linter && Test (Parallers)
- [x] Build
- [x] GitLab registry
- [x] Check LICENSE
- [x] Notify to slack
- [x] Use GitLab CI Template (https://github.com/batazor/gitlab-ci-jobs)
- [ ] Cache dependencies
- [ ] GitLab Release
- [ ] Badger

### Forkflow

- [ ] [Automatically stop environments after a specified period](https://about.gitlab.com/releases/2020/02/22/gitlab-12-8-released/#automatically-stop-environments-after-a-specified-period)
- [ ] review apps
- [ ] HotFix (Need rapid deploy to master)
- [ ] Research GitLab auto-deploy
- [ ] Cannary deploy
- [x] DAST

### artifacts

- [ ] [Automatically bring in artifacts from cross-project jobs](https://about.gitlab.com/releases/2020/02/22/gitlab-12-8-released/#automatically-bring-in-artifacts-from-cross-project-jobs)

### intergration

- [x] sentry
- [ ] Knative

### k8s

- [x] intergration
- [x] logs
- [ ] metrics

### Environment

- [x] Yandex
  - [ ] Improt/Export alert/dashboard?
- [ ] AWS
- [ ] Google
- [ ] Minikube??? (From CI)

### Link:

- https://medium.com/@TianchenW/run-gitlab-pipeline-dry-f9fd65c28a23
- https://about.gitlab.com/blog/2017/11/27/go-tools-and-gitlab-how-to-do-continuous-integration-like-a-boss/
