### ISSUE TITLE
grpc: improve

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#53]
### ToDo

- [x] add a message -> start service
- [x] add logging
- [x] add opentracing
- [x] custom message about of error https://github.com/graph-gophers/graphql-go#custom-errors
- [ ] ui https://github.com/gusaul/grpcox
