### ISSUE TITLE
add method: links

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#55]
### ToDo:

Store:
- [x] Add method: get links for all DB's
- [x] Add test

API:
- [x] gRPC-gateway
- [x] http
- [x] GraphQL

Fix:
- [x] Fix generate proto
- [ ] Fix test coverage
- [x] Fix generate GraphQL
- [x] API for DGraph
