### ISSUE TITLE
auth service

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#580]
### Additional context

- ...

### To-Do

- [ ] Run kratos in k8s
- [ ] Intergate UI and Kratos
  - [ ] Login
  - [ ] Logout
  - [ ] Registration
- [ ] UI mode: auth/guest
- [ ] Admin
  - [ ] Get List

### API Kratos

- [x] Login
- [x] Logout
- [x] Registration
- [ ] Profile management
  - [x] update first name
  - [ ] update avatar
- [ ] Credentials Management
  - [ ] add a new recovery email
  - [x] change password
- [x] Account Recovery
  - [x] password reset
- [x] Email Verification
- [ ] Two Factor Authentication
- [x] "Sign in with Google" and "Sign in with GitHub"

###### UI

- [x] Auth
  - [x] Login
  - [x] Logout
  - [x] Registration
- [x] Dashboard
- [x] Admin
- [x] User Profile

### Docs

- [ ] https://habr.com/ru/company/avanpost/blog/480576/
- [ ] https://habr.com/ru/company/custis/blog/248649/
- [JWT Header](https://habr.com/ru/post/502702/)

### Tool

- [x] [kratos](ory.sh/kratos)
- [ ] https://www.ory.sh/keto/
- [ ] [Dex](https://github.com/dexidp/dex)
- [ ] https://github.com/casbin/casbin
