### ISSUE TITLE
monitoring: try loki

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#70]
https://grafana.com/oss/loki/

Release v1.6.0 - https://github.com/grafana/loki/releases/tag/v1.6.0

- [ ] https://medium.com/@yannig.perre_32769/loki-centralization-of-logs-using-the-prometheus-way-3e2d3c7f6227

### TODO

- [x] monitoring docker-container (docker-compose)
- [x] dashboard for application
- [ ] parse json
  - [ ] Nginx as example
- [ ] Prometheus metrics
- [x] OpenTracing
