### ISSUE TITLE
New service: telecast

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#783]
Show log service in web-interface

### TODO:

- [ ] Subscribe to MQ
- [ ] Send event to web-page
- [ ] web-page - create a new link

![t](https://user-images.githubusercontent.com/1643797/91724581-2c62ea80-eba6-11ea-841a-69f72fc63738.png)

### Docs

- [ ] https://centrifugal.github.io/centrifugo/blog/quic_web_transport/
