### ISSUE TITLE
write docs

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#801]
### Additional context

- ...

### To-Do

- [x] use hugo
- [x] https://hugoloveit.com/
- [x] add domain for gitlab page `shortlink.[domain]`
- [x] add to GitLab CI (or github)
