### ISSUE TITLE
opentracing step 2

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#804]
### Additional context

- ...

### To-Do

- [x] logger DB (https://github.com/luna-duclos/instrumentedsql)
- [z] spark-dependencies

### Docs

- [x] [Edgar: Solving Mysteries Faster with Observability](https://netflixtechblog.com/edgar-solving-mysteries-faster-with-observability-e1a76302c71f)
- [x] [Tracing at Slack: Thinking in Causal Graphs](https://slack.engineering/tracing-at-slack-thinking-in-causal-graphs)
