### ISSUE TITLE
Write driwer Cloud Native Storage (CAS)

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#817]
### Additional context

- ...

### To-Do

- [ ] [OpenEBS](https://openebs.io/) is a Kubernetes-based tool to create stateful applications using Container Attached Storage.
- [ ] Also Kubernetes-based, [Rook](https://rook.io/) offers self-managed, scaling, and healing storage services.
- [ ] [Cockroach Labs](https://www.cockroachlabs.com/) uses Distributed SQL to make databases portable and scalable.
- [ ] [Rancher Longhorn](https://longhorn.io/) offers persistent storage for Kubernetes.

### Docs

- [ ] [cloud-native-storage-beginners](https://about.gitlab.com/blog/2020/09/10/cloud-native-storage-beginners/)
