### ISSUE TITLE
Container Storage Interface (CSI)

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#818]
### Additional context

- ...

### To-Do

- [x] Init
- [ ] Write custom store
- [ ] Test
- [ ] Post in Hugo

### DOCS

- [ ] https://www.architecting.it/blog/container-storage-interface/
