### ISSUE TITLE
try gitlab

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#851]
### Additional context

- ...

### To-Do

- [x] https://about.gitlab.com/releases/2020/09/22/gitlab-13-4-released/
- [x] https://about.gitlab.com/releases/2020/10/22/gitlab-13-5-released/
- [x] https://about.gitlab.com/releases/2020/11/22/gitlab-13-6-released/
- [ ] [How to secure your Kubernetes pods using GitLab Container Network Security](https://about.gitlab.com/blog/2020/10/23/container-network-security-is-important/)
- [ ] [How to use HashiCorp Waypoint to deploy with GitLab CI/CD](https://about.gitlab.com/blog/2020/10/15/use-waypoint-to-deploy-with-gitlab-cicd/)

### CI

- [ ] Fix job `container_scanning`
