### ISSUE TITLE
store: optimization work with table

### ISSUE THREAD

**Issue by batazor** [batazor/shortlink#880]
##### Docs

- [ ] https://www.honeybadger.io/blog/easy-rails-database-scaling-wins/

##### TODO

- [ ] Use UUID as id
- [ ] TTL
  - [ ] Postgres
    - [ ] [pg_partman](https://github.com/pgpartman/pg_partman)
